### PR TITLE
Docs update and notification fix

### PR DESCRIPTION
**Pull request by levouh**
Two changes:

1. Add note in doc. about `conceallevel` being required to hide emphasis markers, "fixes" #124
2. Fix default checks for 0/1 instead of Lua-style boolean for `vim.fn.executable` (used with notifications in this case, but checked elsewhere and other places look good from what I can tell too)

### CODE REVIEW

**Comment by levouh** [comment]
Don't merge this, something is up with my `md2vim` it looks like.

**Comment by levouh** [comment]
Not 100% what is up with `md2vim`, do you use a special build @kristijanhusak? I just downloaded the one from [here](https://github.com/FooSoft/md2vim).

**Comment by kristijanhusak** [comment]
Good catch. I'm using Linux so first if always worked for me.

I'm downloading latest with go: `go get github.com/FooSoft/md2vim@latest`. I think prepackaged builds are outdated.

**Comment by levouh** [comment]
Should be good to go now.

**Comment by kristijanhusak** [comment]
Thanks!

**Pull request merged**
